apiVersion: v1
kind: Secret
metadata:
  name: preprocess-worker-secret
  namespace: docprep-cloud
  labels:
    app.kubernetes.io/name: preprocess-worker
    app.kubernetes.io/part-of: docprep-cloud
type: Opaque
stringData:
  SPRING_RABBITMQ_USERNAME: CHANGE_ME
  SPRING_RABBITMQ_PASSWORD: CHANGE_ME
  RABBITMQ_AMQP_URI: amqp://CHANGE_ME:CHANGE_ME@rabbitmq:5672/%2F
  MINIO_ACCESS_KEY: CHANGE_ME
  MINIO_SECRET_KEY: CHANGE_ME
  WORKER_INTERNAL_TOKEN: CHANGE_ME
