apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: docprep-cloud
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/part-of: docprep-cloud
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: amqp
    - name: management
      port: 15672
      targetPort: management
    - name: prometheus
      port: 15692
      targetPort: prometheus
