apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yml
  - backend-api/configmap.yml
  - backend-api/deployment.yml
  - backend-api/service.yml
  - preprocess-worker/configmap.yml
  - preprocess-worker/deployment.yml
  - preprocess-worker/service.yml
  - preprocess-worker/triggerauthentication.yml
  - preprocess-worker/scaledobject.yml
  - frontend/deployment.yml
  - frontend/service.yml
  - nginx/configmap.yml
  - nginx/deployment.yml
  - nginx/service.yml
  - nginx/ingress.yml
  - postgres/deployment.yml
  - postgres/service.yml
  - rabbitmq/configmap.yml
  - rabbitmq/deployment.yml
  - rabbitmq/service.yml
  - minio/deployment.yml
  - minio/service.yml
  - minio/bucket-job.yml
  - monitoring/prometheus-rbac.yml
  - monitoring/prometheus-configmap.yml
  - monitoring/prometheus-deployment.yml
  - monitoring/prometheus-service.yml
  - monitoring/kube-state-metrics-rbac.yml
  - monitoring/kube-state-metrics-deployment.yml
  - monitoring/kube-state-metrics-service.yml
  - monitoring/node-exporter-daemonset.yml
  - monitoring/node-exporter-service.yml
  - monitoring/grafana-configmap.yml
  - monitoring/grafana-deployment.yml
  - monitoring/grafana-service.yml
  - monitoring/otel-collector-configmap.yml
  - monitoring/otel-collector-deployment.yml
  - monitoring/otel-collector-service.yml
