apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: docprep-cloud
  labels:
    app.kubernetes.io/name: node-exporter
    app.kubernetes.io/part-of: docprep-cloud
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: node-exporter
  ports:
    - name: metrics
      port: 9100
      targetPort: metrics
