location /grafana/ {
    resolver 127.0.0.11 valid=10s ipv6=off;
    set $grafana_upstream http://grafana:3000;
    proxy_pass $grafana_upstream;
    include /etc/nginx/snippets/proxy.conf;
}

location /jaeger/ {
    resolver 127.0.0.11 valid=10s ipv6=off;
    set $jaeger_upstream http://jaeger:16686;
    proxy_pass $jaeger_upstream;
    include /etc/nginx/snippets/proxy.conf;
}
