location /api/ {
    include /etc/nginx/snippets/proxy.conf;
    proxy_pass http://backend_api;
}

location /oauth2/ {
    include /etc/nginx/snippets/proxy.conf;
    proxy_pass http://backend_api;
}

location /login/oauth2/ {
    include /etc/nginx/snippets/proxy.conf;
    proxy_pass http://backend_api;
}

location /v3/api-docs {
    include /etc/nginx/snippets/proxy.conf;
    proxy_pass http://backend_api;
}

location /swagger-ui/ {
    include /etc/nginx/snippets/proxy.conf;
    proxy_pass http://backend_api;
}

location = /swagger-ui.html {
    include /etc/nginx/snippets/proxy.conf;
    proxy_pass http://backend_api;
}
